---
title: "Gov 50 Final Project"
author: "Anis Batrisya Azlan"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested to analyze the effect of lowering the voting age to the overall voter turnout in Malaysia from General Election 14 (2018) to General Election 15 (2022)



# Project Milestone 2 
My research examines the impact of lowering the voting age from 21 to 18 on overall voter turnout in Malaysia, focusing on the newly eligible young voter demographic. I  hypothesize that reducing the voting age will lead to increased voter turnout among this group, based on the theory of political mobilization which posits that younger voters are more likely to vote when given the opportunity, driven by a desire to utilize newly acquired rights and influenced by targeted political campaigns. The primary explanatory variable is the "Policy Age of Voting," which shifted from 21 in General Election 14 to 18 in General Election 15, providing a natural variation. I will also account for confounding variables like "Political Awareness at School" and "Socioeconomic Status (SES) Post-COVID-19" to isolate the effect of the voting age change. The dependent variable, "Overall Voters Turnout," will be measured by the percentage of eligible voters who participate in the elections. Supporting data would show increased turnout among the 18-21 age group in General Election 15, while a lack of change or a decrease in turnout would challenge the hypothesis.

The voter turnout is easily accessible through github under "Tindak Malaysia".The socioeconomic conditions could be accessed through the government portal. 
